### ISSUE TITLE
Less restrictive license

### ISSUE THREAD

**Issue by solhuebner** [RalphBacon/224-Superior-Serial.print-statements#1]
Great project!

Would you mind changing to a slightly less restrictive license like LGPL?

MIT would be awesome but at least LGPL would broaden in which projects it could be used :)

Regards,
Sol

**Comment by RalphBacon** [comment]
Is it the Open Source requirement you're worried about, or something else, Sol? A bit of detail might easily make me change my licence (for this repository)!

**Comment by solhuebner** [comment]
I have no issues with releasing improvements made for your library but might not be comfy releasing all parts of all of my projects under the restrictive GPL. With at least the LGPL I could release projects under the MIT license with yours on the "side". Otherwise, it would prevent releasing projects under less restrictive licenses and I think a lot of projects could benefit from better debugging ;)

**Comment by RalphBacon** [comment]
No problem. I've updated the licence to MIT. 

You should be aware that the debugging method I show doesn't cater for the following, two parameter construct:
`Serial.println(myValue, HEX);`

However, if you read the comments in the video you will see that I have suggested an improvement that does allow for this.

_**Extract from comment to Jan Bunk:**_

If you change the definition of each `debug(x)` and `debugln(x)` to:

`debugln(x, ...)  // at least one parameter, maybe more`

then change the underlying Serial.print to:

`Serial.println(x, ##__VA_ARGS__);`

you can use:

`debugln("this is a string");`
`debugln(42);`
`debugln(42, HEX);`

Feel free to amend/fork as required.

**Comment by solhuebner** [comment]
Very cool. Thank you :)
